server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
  shutdown: graceful
spring:
  lifecycle:
    timeout-per-shutdown-phase: 15s
  application:
    name: catalog-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:9000
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: false
      retry:
        initial-interval: 1000
        max-attempts: 6
        max-interval: 2000
        multiplier: 1.1




  datasource:
    url: jdbc:postgresql://localhost:5432/polardb_catalog
    username: user
    password: password
#    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 2000

  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: "refresh"

polar:
  greeting: Welcome to the Local Book Catalog!
