apiVersion: apps/v1
kind: Deployment
metadata:
  name: polar-catalog-postgres
  labels:
    db: polar-catalog-postgres
spec:
  selector:
    matchLabels:
      db: polar-catalog-postgres
  template:
    metadata:
      labels:
        db: polar-catalog-postgres

    spec:
      containers:
        - name: polar-catalog-postgres
          image: "postgres:14.12"
          env:
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: polardb_catalog

          resources:
            requests:
              cpu: 100m
              memory: 60Mi
            limits:
              cpu: 200m
              memory: 120Mi
