apiVersion: v1
kind: Service
metadata:
  name: polar-catalog-postgres
  labels:
    db: polar-catalog-postgres
spec:
  type: ClusterIP
  selector:
    db: polar-catalog-postgres
  ports:
    - name: http
      protocol: TCP
      port: 5432
      targetPort: 5432