name: Build Image And Push To Registry
on: release
#  schedule:
#    - cron: '*/8 * * * *'
#  push:
#    branches: ['develop']
#    paths: ['./my-java-image/**']

jobs:
  build-and-push:
    name: Docker Build Image And Push To Registry
    runs-on: ubuntu-22.04
    permissions:
      contents: read
#      security-events: write
      packages: write
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_IO_USER }}
          password: ${{ secrets.GHCR_IO_TOKEN }}

      - # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./my-java-image/.
          push: true
          tags: ghcr.io/ifeanyichukwuotiwa-sports/my-java-image:1.0.0
#          tags: ghcr.io/ifeanyichukwuotiwa-sports/<YOUR_REPO>/<YOUR_IMAGE>:<TAG>